### PR TITLE
Added Objective-C support

### PR DESCRIPTION
**Pull request by Gringox**
Hello @PiXeL16, here is the PR for issue #33.

Please do test it before merging, I have not done a PR before and I do not want to break anything 😅.

Thank you again.

### CODE REVIEW

**Comment by Gringox** [comment]
I ran the tests locally with:

`xcodebuild -workspace RevealingSplashView.xcworkspace -scheme "RevealingSplashView" -destination "OS=10.3.1,name=iPhone 6s Plus" test GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES | xcpretty -c`

And I believe it did worked because I got the following output:

screen shot 2017-06-27 at 9 10 44 am

I do not know what went wrong.

**Comment by PiXeL16** [comment]
Awesome thanks! 🎉 Will fix `CI` in separate PR!

**Comment by PiXeL16** [comment]
BTW pushed version `0.4.0` with your fix https://cocoapods.org/pods/RevealingSplashView 👍

**Comment by Gringox** [comment]
Nice! Thank you! 👍

**Pull request merged**
