### PR TITLE
Update for Xcode 10.2 / Swift 5

### PR DESCRIPTION
**Pull request by weakfl**
- bump version
 - bump `.swift-version`
 - update podspec
 - update Podfile
 - update project to recommended settings
 - convert framework to Swift 5
 - convert sample to Swift 5
 - fix warnings

```
$ pod lib lint

 -> RevealingSplashView (0.8.0)
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | [iOS] xcodebuild:  note: Planning build
    - NOTE  | [iOS] xcodebuild:  note: Constructing build description

RevealingSplashView passed validation.
```

### CODE REVIEW

**Comment by weakfl** [comment]
@PiXeL16?

**Comment by jeffssss** [comment]
@PiXeL16

**Comment by KarlChow92** [comment]
@PiXeL16

**Comment by weakfl** [comment]
@PiXeL16 bump...

**Comment by weakfl** [comment]
Thanks for merging @PiXeL16. Could you please also make a new release and push it to cocoapods?

**Comment by blackcolt** [comment]
@PiXeL16 Please publish new version, can't update to Swift 5.0

**Comment by PiXeL16** [comment]
You can just point your dependency manager to Master, not the one published and it should be fine. I gave successor acces to @weakfl Since I dont have time to maintain this repo anymore. 
@weakfl Would you be able to publish the new version?

**Comment by weakfl** [comment]
@PiXeL16 @blackcolt I'll look into it...

**Comment by weakfl** [comment]
@PiXeL16 I'll also need permissions on cocoapods.org, I've sent you an email with my account details...

**Comment by PiXeL16** [comment]
Done! Thank you

**Pull request merged**
