### PR TITLE
Add SPM

### PR DESCRIPTION
**Pull request by relisiuol**

### CODE REVIEW

**Comment by rollyceballos** [comment]
@PiXeL16 you can have this merged to add support for SPM. would be glad to migrate our codebase to SPM using this.

**Comment by PiXeL16** [comment]
Done

**Comment by relisiuol** [comment]
Hello,

Thank you for merging my pull request! To enable Xcode to retrieve the latest code via the Swift Package Manager (SPM), could you please create a new tag for this update? Version 0.9.1 would be appropriate.

In the meantime, if any developers need access to this update, they can use my forked repository: https://github.com/relisiuol/RevealingSplashView

Regards

**Comment by lchamp** [comment]
Tag 0.9.1 added @relisiuol 

Edit: I've now _backdated_ the 0.9.1 tag to the commit date (instead of today)

**Pull request merged**
